### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by briatte** [FATelarico/ctv-network-submitted#1]
Dear @FATelarico (and other authors),

Do you need help with this CRAN task view? 

I have a long list of network packages on this page:

https://github.com/briatte/awesome-network-analysis

Thanks to @jhollway for mentioning this draft.

Best wishes,

François

**Comment by krivit** [comment]
@briatte, thanks, I didn't know about this list! We should definitely cross-reference what's in the draft with the list and see if there is anything we've missed.

**Comment by FATelarico** [comment]
I also thank you for the link and the amazing work you've put into this. I went through the list of `R` packages and managed to find a few more packages for our list. 

Thank you once again!
