### ISSUE TITLE
Submission ready (?)

### ISSUE THREAD

**Issue by FATelarico** [FATelarico/ctv-network-submitted#2]
Hello everyone! 

I am opening this issue to check up with everyone on whether we feel comfortable with submitting this version to CTV team.

On my side everything's good to go

**Comment by krivit** [comment]
Looking at the latest version, the organisation is still a bit awkward:
* Shouldn't modelling include blockmodelling? Perhaps we could rename the "Modelling" section to "Statistical Modelling" to distinguish from EDA?
* "Main tools" section seems to be a bit arbitrary. We can certainly justify `igraph` and maybe Statnet (as a suite of packages), but why `manynet`? Do we really need it?

|package | downloads| percentile|
|:-------|---------:|----------:|
|igraph  |    372396|   99.53256|
|sna     |     24614|   97.68064|
|network |     20870|   97.46655|
|ergm    |      5620|   95.10259|
|statnet |      3294|   93.78769|
|ergm.multi |      2326|   92.61731|
|manynet |      1020|   88.13559|


There are also some minor issues, which I can fix:

* `sna` doesn't actually build on `network`. It can make use of `network`, but internally it uses different data structures.
* `latentnet` is probably in modelling and/or group detection category.

**Comment by krivit** [comment]
By the looks of it, the whole "Other" section is actually model-based clustering.

**Comment by krivit** [comment]
How about instead of "Main tools", we have a section like "Ecosystems", since you have the `igraph` and the Statnet ecosystems.

**Comment by krivit** [comment]
Should Layouts be a subsection of Visualisation?

**Comment by jhollway** [comment]
I think "Ecosystems" makes sense (though there are several packages that cut across). A third 'ecosystem' could be the '[stocnet](https://github.com/stocnet)' packages, which includes `{manynet}`, `{goldfish}`, and `{RSiena}` etc. I think `{tidygraph}` could appear here too, but I think `{graph}` should be left off since it is not on CRAN but instead BioConductor.

I would be fine with an EDA section, renaming/moving model-based clustering, and putting layouts down the hierarchy.

**Comment by FATelarico** [comment]
Thank you for your quick replies. Here are my thoughts on these issues:

-------------------------------

> Shouldn't modelling include blockmodelling?

I guess most people think of blockmodeling more like as clustering (like community detection) and less as 'modeling' the network like in ERGM. So I put it under the *model-based clustering* heading.

> Should Layouts be a subsection of Visualisation?

Agreed

> Perhaps we could rename the "Modelling" section to "Statistical Modelling" to distinguish from EDA?

This seems reasonable

> "Main tools" section seems to be a bit arbitrary. We can certainly justify `igraph` and maybe Statnet (as a suite of packages), but why `manynet`? Do we really need it?

It may be best to rename the section to 'Ecosystems' and replace manynet for [`stocnet`](https://github.com/stocnet) and, perhaps, list some of the packages liek for `sna` and and `igraph`. However, I would not be sure of which packages would be worth mentioning explicitly as I have not used them extensively.

------------------------

Except for the last point, I implemented the other changes in this commit: https://github.com/FATelarico/ctv-network/commit/c0d6dc8c1735130bd9a8e3c792ebaf3d29e1368d. Namely:

1. The *Others* heading was renamed *Model-Based Clustering*
2. *Blockmodeling* was moved to that new section
3. *Main tools* was renamed into *Ecosystems* and the text was adapted to reflect this new framing
4. The connection between `sna` and `network` (i.e., both belong to the `statnet` ecosystem) was clarified.
5. *Layouts* was demoted to a subsection fo *Visualisation*, which now is more structured.

In addition, I noticed that `latenetwork` was marked as TODO and took care of that.

**Comment by FATelarico** [comment]
With commit [`b06a3e4`](https://github.com/FATelarico/ctv-network/commit/b06a3e445a16b1224e0200ac6726424255155f91) (and [`eafe94b`](https://github.com/FATelarico/ctv-network/commit/eafe94bccdff490128ce97ade7f62e52d96bcb86), which simply correct the version date) I have implemented a few more changes. Given that they are minor in nature and that there were no more comments I will proceed with notifying the CTV editorial team.

Thank you all for your support and immensely valuable expertise.
